### ISSUE TITLE
Assumptions with default location

### ISSUE THREAD

**Issue by didyouexpectthat** [Unimatrix0/update_ombi#3]
It would be nice to be able to keep updated with latest master for all future enhancements to update_ombi; but doing so overwrites changes to update_ombi.sh, which include modifying values like the default location of Ombi. 

In `update_ombi.sh`, have default values. Perhaps in the same directory as `update_ombi.sh`, it could look for `update_ombi.conf`, `source update_ombi.conf`,  and pull values from there to overwrite any default values.
Add `update_ombi.conf` to `.gitignore` 

What do you think?

**Comment by Unimatrix0** [comment]
Resolved by #4
